import './style.css';
import { AppState, BomLine, Part, Project, csvEscape, makeId, parseBom, partsCsv, statusFor } from './domain';
import { download, loadState, saveState } from './storage';
import { captureLicense, hasLicense, restoreLicense, verifyLicense } from './license';

captureLicense();
let state: AppState = loadState(); let undo: (() => void) | undefined; let notice = '';
const root = document.querySelector<HTMLDivElement>('#app')!;
const active = () => state.projects.find((project) => project.id === state.activeProjectId);
const persist = () => { saveState(state); render(); };
const esc = (value: string) => value.replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]!));
function modal(title: string, body: string) { return `<dialog class="sheet" aria-label="${esc(title)}"><form method="dialog"><header><h2>${esc(title)}</h2><button class="icon" value="cancel" aria-label="Close">×</button></header>${body}</form></dialog>`; }
function appShell(content: string) { return `<a class="skip" href="#main">Skip to workspace</a><header class="top"><a class="brand" href="#inventory" aria-label="Bench Bin BOM home"><span class="brand-mark" aria-hidden="true">▣</span><span>Bench Bin <b>BOM</b></span></a><nav aria-label="Product"><button data-route="inventory">Bench stock <small>${state.parts.length}</small></button><button data-route="projects">Builds <small>${state.projects.length}</small></button><button data-route="about">About</button></nav><button class="primary compact" data-action="new-project">New build</button></header><main id="main">${content}</main><div class="toast" aria-live="polite">${notice ? `${esc(notice)} ${undo ? '<button data-action="undo">Undo</button>' : ''}` : ''}</div>`; }
function inventory() { const rows = state.parts.length ? state.parts.map((part) => `<li class="part-row"><div class="part-photo">${part.photo ? `<img src="${part.photo}" alt="Photo of ${esc(part.name)}">` : '<span aria-hidden="true">●</span>'}</div><div><strong>${esc(part.name)}</strong><span>${esc(part.value || 'No value recorded')}</span></div><div class="number"><b>${part.quantity}</b><span>on hand</span></div><div class="bin">${esc(part.bin || 'Unbinned')}</div><button class="quiet" data-edit-part="${part.id}">Edit</button></li>`).join('') : `<li class="empty"><span aria-hidden="true">▦</span><h2>Your bench is clear</h2><p>Add what is already in the drawers. A build can then tell you what is missing before you begin.</p><button class="primary" data-action="new-part">Add first part</button></li>`;
 return appShell(`<section class="intro"><div><p class="eyebrow">Drawer stock, made build-ready</p><h1>Know what’s on the bench before you order.</h1><p>Keep a lightweight record of bins and parts, then compare it directly with a project BOM.</p><div class="action-row"><button class="primary" data-action="new-part">Add a part</button><button class="secondary" data-action="import-parts">Import CSV</button></div></div><aside class="diorama" aria-label="A project paper and component drawer illustration"><span class="paper-line">Project list</span><span class="mini-bin b1">10k</span><span class="mini-bin b2">ESP</span><span class="mini-bin b3">M3</span></aside></section><section class="panel stock"><div class="section-heading"><div><p class="eyebrow">Bench stock</p><h2>${state.parts.length} recorded parts</h2></div><button class="quiet" data-action="export-parts" ${state.parts.length ? '' : 'disabled'}>Export CSV</button></div><ul class="parts">${rows}</ul></section>`); }
function projects() { const cards = state.projects.length ? state.projects.map((project) => { const statuses = project.bom.map((line) => statusFor(state.parts,line)); const shortage = statuses.filter((s) => !s.ready).length; return `<article class="project-card"><p class="eyebrow">${shortage ? `${shortage} shortage${shortage === 1 ? '' : 's'}` : 'Ready to pull'}</p><h2>${esc(project.name)}</h2><p>${project.bom.length} BOM lines · updated ${new Date(project.updatedAt).toLocaleDateString()}</p><button class="secondary" data-open-project="${project.id}">Open pull list</button></article>`; }).join('') : `<div class="empty"><span aria-hidden="true">☷</span><h2>No builds yet</h2><p>Paste a BOM from your project notes and check it against the bench in seconds.</p><button class="primary" data-action="new-project">Start a build</button></div>`; return appShell(`<section class="page-heading"><p class="eyebrow">Project cards</p><h1>Builds</h1><p>Every build has one straightforward question: can I start with what I have?</p></section><section class="project-grid">${cards}</section>`); }
function build(project: Project) { const lines = project.bom.map((line) => { const result = statusFor(state.parts,line); return `<li class="bom-row ${result.ready ? 'ready' : 'short'}"><div class="status-symbol" aria-label="${result.ready ? 'Ready' : 'Short'}">${result.ready ? '✓' : '!'}</div><div><strong>${esc(line.part)}</strong><span>${esc(line.value || 'Value not specified')}${line.note ? ` · ${esc(line.note)}` : ''}</span>${line.substitute ? `<small>Substitute: ${esc(line.substitute)} — review electrical fit yourself.</small>` : ''}</div><div class="number"><b>${line.needed}</b><span>needed</span></div><div class="number"><b>${result.stocked}</b><span>on hand</span></div><div><b>${result.ready ? 'Ready' : `${result.shortage} short`}</b></div><button class="quiet" data-edit-line="${line.id}">Edit</button></li>`; }).join(''); const short = project.bom.filter((line) => !statusFor(state.parts,line).ready).length; return appShell(`<section class="build-head"><div><a class="back" href="#projects">← All builds</a><p class="eyebrow">Project pull card</p><h1>${esc(project.name)}</h1><p>${esc(project.notes || 'No project note yet.')}</p></div><div class="readiness ${short ? 'short' : 'ready'}"><b>${short ? `${short} line${short === 1 ? '' : 's'} to source` : 'Ready to pull'}</b><span>${short ? 'Review shortages before starting.' : 'Everything is recorded on the bench.'}</span></div></section><section class="pull-actions"><button class="primary" data-action="new-line">Add BOM line</button><button class="secondary" data-action="import-bom">Paste / import BOM</button><button class="secondary" data-action="print">Print pull list</button><button class="quiet" data-action="edit-project">Edit build</button></section><section class="panel bom"><div class="table-labels" aria-hidden="true"><span></span><span>Part</span><span>Need</span><span>Stock</span><span>Status</span><span></span></div><ul>${lines || '<li class="empty"><h2>No BOM lines</h2><p>Add parts or paste CSV to make this build checkable.</p><button class="primary" data-action="import-bom">Paste BOM</button></li>'}</ul></section><aside class="safety-note"><b>Substitutes need your review.</b> Electrical substitutions are notes, not safety advice. Check ratings, pinouts, and fit before use.</aside>`); }
function about() { return appShell(`<section class="page-heading"><p class="eyebrow">Local-first bench tool</p><h1>Made for the moment before a build.</h1><p>Bench Bin BOM saves its data only in this app on your device. It is not a supplier, purchasing tool, or electrical safety authority.</p></section><section class="panel prose"><h2>One-time unlock</h2><p>The free app records up to 40 stock parts and two builds. The Bench Pass one-time unlock removes those limits and adds print layout presets. Core data export is always free.</p><a class="primary link-button" href="https://api.sociobot.in/api/v1/products/bench-bin-bom/checkout">Buy Bench Pass</a><p>${hasLicense() ? 'Bench Pass license saved on this device.' : 'Already own it?'} <button class="inline" data-action="restore-license">Restore a license</button></p><p><a href="#privacy">Privacy</a> · <a href="#terms">Terms</a></p></section>`); }
function legal(kind: 'privacy'|'terms') { const privacy = kind === 'privacy'; return appShell(`<article class="legal"><a class="back" href="#about">← Back</a><h1>${privacy ? 'Privacy' : 'Terms'}</h1>${privacy ? '<p>Bench Bin BOM stores your parts, photos, projects, and license token locally in this app’s device storage. We do not run analytics or send your inventory to us. License verification contacts Sociobot no more than once per day when you restore or use a paid license.</p><p>CSV exports are created only when you choose Export. Removing app storage removes the local record.</p>' : '<p>Bench Bin BOM is an offline planning utility. It does not guarantee stock accuracy, component compatibility, or electrical safety. Review substitutions, ratings, pinouts, and fit yourself. Purchases are one-time license unlocks sold by Sociobot / Dodo, merchant of record; refunds revoke the license.</p>'}</article>`); }
function render() { const hash = location.hash.slice(1); const project = hash.startsWith('build/') ? state.projects.find((p) => p.id === hash.slice(6)) : undefined; root.innerHTML = hash.startsWith('build/') ? (project ? build(project) : appShell('<section class="empty"><h1>That build is not here</h1><p>It may have been removed from this device.</p><a class="primary link-button" href="#projects">See builds</a></section>')) : hash === 'projects' ? projects() : hash === 'about' ? about() : hash === 'privacy' || hash === 'terms' ? legal(hash) : inventory(); bind(); }
const canAdd = (kind: 'part'|'project') => hasLicense() || (kind === 'part' ? state.parts.length < 40 : state.projects.length < 2);
function openDialog(html: string) { document.body.insertAdjacentHTML('beforeend', html); const dialog = document.body.querySelector<HTMLDialogElement>('dialog:last-of-type')!; dialog.showModal(); dialog.addEventListener('close', () => dialog.remove()); return dialog; }
function partDialog(part?: Part) { const p = part || { id: makeId(), name:'', value:'', quantity:1, bin:'', note:'' }; const dialog = openDialog(modal(part ? 'Edit part' : 'Add a part', `<label>Part name<input required name="name" value="${esc(p.name)}" autocomplete="off"></label><div class="form-grid"><label>Value / variant<input name="value" value="${esc(p.value)}"></label><label>Quantity on hand<input required type="number" min="0" name="quantity" value="${p.quantity}"></label></div><label>Bin location<input name="bin" value="${esc(p.bin)}" placeholder="A2 · top drawer"></label><label>Note<input name="note" value="${esc(p.note)}" placeholder="Package, rating, or condition"></label><label>Photo (stored only on this device)<input name="photo" type="file" accept="image/*"></label><p class="error" aria-live="polite"></p><footer><button class="secondary" value="cancel">Cancel</button>${part ? '<button class="danger" type="button" data-delete-part="true">Remove</button>' : ''}<button class="primary" value="default">Save part</button></footer>`)); dialog.addEventListener('submit', async (event) => { event.preventDefault(); if (!part && !canAdd('part')) { dialog.querySelector('.error')!.textContent = 'The free bench holds 40 parts. Bench Pass removes this limit.'; return; } const form = new FormData(event.target as HTMLFormElement); const file = form.get('photo') as File; let photo = p.photo; if (file?.size) photo = await new Promise<string>((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(file); }); const next: Part = { ...p, name:String(form.get('name')).trim(), value:String(form.get('value')).trim(), quantity:Number(form.get('quantity')), bin:String(form.get('bin')).trim(), note:String(form.get('note')).trim(), photo }; if (part) state.parts = state.parts.map((item) => item.id === p.id ? next : item); else state.parts.push(next); dialog.close(); persist(); }); dialog.querySelector('[data-delete-part]')?.addEventListener('click', () => { state.parts = state.parts.filter((item) => item.id !== p.id); notice = `${p.name} removed.`; undo = () => { state.parts.push(p); }; dialog.close(); persist(); }); }
function projectDialog(project?: Project) { const p = project || { id: makeId(), name:'', notes:'', bom:[], updatedAt:new Date().toISOString() }; const dialog = openDialog(modal(project ? 'Edit build' : 'Start a build', `<label>Build name<input required name="name" value="${esc(p.name)}" placeholder="Garage sensor"></label><label>Build note<textarea name="notes" rows="3" placeholder="What is this for?">${esc(p.notes)}</textarea></label><p class="error" aria-live="polite"></p><footer><button class="secondary" value="cancel">Cancel</button><button class="primary" value="default">${project ? 'Save build' : 'Create pull card'}</button></footer>`)); dialog.addEventListener('submit', (event) => { event.preventDefault(); if (!project && !canAdd('project')) { dialog.querySelector('.error')!.textContent = 'The free bench includes two builds. Bench Pass removes this limit.'; return; } const form = new FormData(event.target as HTMLFormElement); const next = { ...p, name:String(form.get('name')).trim(), notes:String(form.get('notes')).trim(), updatedAt:new Date().toISOString() }; if (project) state.projects = state.projects.map((item) => item.id === p.id ? next : item); else { state.projects.push(next); state.activeProjectId = next.id; } dialog.close(); saveState(state); location.hash = `build/${next.id}`; render(); }); }
function bomDialog(line?: BomLine) { const project = active(); if (!project) return; const l = line || { id:makeId(), part:'', value:'', needed:1, substitute:'', note:'' }; const dialog = openDialog(modal(line ? 'Edit BOM line' : 'Add BOM line', `<label>Part name<input required name="part" value="${esc(l.part)}"></label><div class="form-grid"><label>Value / variant<input name="value" value="${esc(l.value)}"></label><label>Quantity needed<input required min="1" type="number" name="needed" value="${l.needed}"></label></div><label>Substitute note<input name="substitute" value="${esc(l.substitute)}" placeholder="Optional — verify fit"></label><label>Build note<input name="note" value="${esc(l.note)}"></label><footer><button class="secondary" value="cancel">Cancel</button>${line ? '<button class="danger" type="button" data-delete-line="true">Remove</button>' : ''}<button class="primary" value="default">Save line</button></footer>`)); dialog.addEventListener('submit', (event) => { event.preventDefault(); const f = new FormData(event.target as HTMLFormElement); const next: BomLine = { id:l.id, part:String(f.get('part')).trim(), value:String(f.get('value')).trim(), needed:Number(f.get('needed')), substitute:String(f.get('substitute')).trim(), note:String(f.get('note')).trim() }; if (line) project.bom = project.bom.map((item) => item.id === l.id ? next : item); else project.bom.push(next); project.updatedAt = new Date().toISOString(); dialog.close(); persist(); }); dialog.querySelector('[data-delete-line]')?.addEventListener('click', () => { project.bom = project.bom.filter((item) => item.id !== l.id); dialog.close(); persist(); }); }
function importDialog(kind: 'parts'|'bom') { const dialog = openDialog(modal(kind === 'bom' ? 'Paste a BOM' : 'Import bench CSV', `<p>Use comma-separated rows. ${kind === 'bom' ? 'Columns: part, value, quantity, substitute, note.' : 'Columns: name, value, quantity, bin, note.'}</p><label>CSV<textarea required name="csv" rows="9" placeholder="part,value,quantity\n10k resistor,1/4W,8"></textarea></label><p class="error" aria-live="polite"></p><footer><button class="secondary" value="cancel">Cancel</button><button class="primary" value="default">Import rows</button></footer>`)); dialog.addEventListener('submit', (event) => { event.preventDefault(); const raw = String(new FormData(event.target as HTMLFormElement).get('csv')); try { const rows = parseBom(raw); if (!rows.length) throw new Error('Add at least one valid row.'); if (kind === 'bom') { const project = active(); if (!project) throw new Error('Open a build first.'); project.bom.push(...rows.map((line) => ({ ...line, id:makeId() }))); project.updatedAt = new Date().toISOString(); } else { if (!hasLicense() && state.parts.length + rows.length > 40) throw new Error('This import exceeds the free 40-part bench limit. Bench Pass removes the limit.'); state.parts.push(...rows.map((line) => ({ id:makeId(), name:line.part, value:line.value, quantity:line.needed, bin:line.substitute, note:line.note }))); } dialog.close(); persist(); } catch (error) { dialog.querySelector('.error')!.textContent = error instanceof Error ? error.message : 'Could not import those rows.'; } }); }
function bind() {
  root.querySelectorAll<HTMLElement>('[data-route]').forEach((button) => button.onclick = () => location.hash = button.dataset.route!);
  root.querySelector('[data-action="new-part"]')?.addEventListener('click', () => partDialog());
  root.querySelector('[data-action="new-project"]')?.addEventListener('click', () => projectDialog());
  root.querySelector('[data-action="import-parts"]')?.addEventListener('click', () => importDialog('parts'));
  root.querySelector('[data-action="import-bom"]')?.addEventListener('click', () => importDialog('bom'));
  root.querySelector('[data-action="new-line"]')?.addEventListener('click', () => bomDialog());
  root.querySelector('[data-action="edit-project"]')?.addEventListener('click', () => { const p = active(); if (p) projectDialog(p); });
  root.querySelector('[data-action="export-parts"]')?.addEventListener('click', () => { download('bench-bin-parts.csv', partsCsv(state.parts)); notice = 'Bench CSV exported.'; render(); });
  root.querySelector('[data-action="print"]')?.addEventListener('click', () => window.print());
  root.querySelector('[data-action="undo"]')?.addEventListener('click', () => { undo?.(); undo = undefined; notice = 'Part restored.'; persist(); });
  root.querySelector('[data-action="restore-license"]')?.addEventListener('click', () => { const dialog = openDialog(modal('Restore Bench Pass', '<label>License token<input required name="license" autocomplete="off"></label><p class="error" aria-live="polite"></p><footer><button class="secondary" value="cancel">Cancel</button><button class="primary" value="default">Restore license</button></footer>')); dialog.addEventListener('submit', async (event) => { event.preventDefault(); const token = String(new FormData(event.target as HTMLFormElement).get('license')); restoreLicense(token); const valid = await verifyLicense(); if (valid) { dialog.close(); notice = 'License restored.'; render(); } else dialog.querySelector('.error')!.textContent = 'That license could not be verified. Check the token and try again.'; }); });
  root.querySelectorAll<HTMLElement>('[data-edit-part]').forEach((button) => button.onclick = () => partDialog(state.parts.find((part) => part.id === button.dataset.editPart)));
  root.querySelectorAll<HTMLElement>('[data-open-project]').forEach((button) => button.onclick = () => { state.activeProjectId = button.dataset.openProject; saveState(state); location.hash = `build/${button.dataset.openProject}`; });
  root.querySelectorAll<HTMLElement>('[data-edit-line]').forEach((button) => button.onclick = () => { const p = active(); const line = p?.bom.find((item) => item.id === button.dataset.editLine); if (line) bomDialog(line); });
}
window.addEventListener('hashchange', render); window.addEventListener('online', () => { notice = 'Back online. Your bench data stayed on this device.'; render(); }); window.addEventListener('offline', () => { notice = 'Offline — everything continues to work locally.'; render(); });
verifyLicense().then((valid) => { if (!valid && hasLicense()) { notice = 'License no longer active. Free tools are still available.'; render(); } });
render();
